"""empty message

Revision ID: a604d17462fc
Revises: 
Create Date: 2024-02-26 16:19:01.089674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a604d17462fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('genreId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('genreId'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('Creator', 'Company'), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('updatedDate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('creators',
    sa.Column('creatorId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('Producer', 'Writer', 'Musician', name='creator_types'), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('profilePic', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('updatedDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('creatorId'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('creator_genres',
    sa.Column('creatorId', sa.Integer(), nullable=False),
    sa.Column('genreId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creatorId'], ['creators.creatorId'], ),
    sa.ForeignKeyConstraint(['genreId'], ['genres.genreId'], ),
    sa.PrimaryKeyConstraint('creatorId', 'genreId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creator_genres')
    op.drop_table('creators')
    op.drop_table('users')
    op.drop_table('genres')
    # ### end Alembic commands ###
