"""empty message

Revision ID: 54f0173970be
Revises: 
Create Date: 2024-02-26 18:00:52.766449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f0173970be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('genreId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('genreId'),
    sa.UniqueConstraint('name')
    )
    op.create_table('types',
    sa.Column('typeId', sa.Integer(), nullable=False),
    sa.Column('typeName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('typeId'),
    sa.UniqueConstraint('typeName')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('Creator', 'Company'), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('updatedDate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('companies',
    sa.Column('companyId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('companyName', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('Pre-Apply', 'Denied', 'Pending', 'Approved'), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('updatedDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('companyId'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('creators',
    sa.Column('creatorId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('Pre-Apply', 'Denied', 'Pending', 'Approved'), nullable=False),
    sa.Column('profilePic', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('updatedDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('creatorId'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('media',
    sa.Column('mediaId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('updatedDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('mediaId')
    )
    op.create_table('creator_genres',
    sa.Column('creatorId', sa.Integer(), nullable=False),
    sa.Column('genreId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creatorId'], ['creators.creatorId'], ),
    sa.ForeignKeyConstraint(['genreId'], ['genres.genreId'], ),
    sa.PrimaryKeyConstraint('creatorId', 'genreId')
    )
    op.create_table('creator_types',
    sa.Column('creatorId', sa.Integer(), nullable=False),
    sa.Column('typeId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creatorId'], ['creators.creatorId'], ),
    sa.ForeignKeyConstraint(['typeId'], ['types.typeId'], ),
    sa.PrimaryKeyConstraint('creatorId', 'typeId')
    )
    op.create_table('opportunities',
    sa.Column('oppId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('targetAudience', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('guidelines', sa.Text(), nullable=True),
    sa.Column('companyId', sa.Integer(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('updatedDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['companyId'], ['companies.companyId'], ),
    sa.PrimaryKeyConstraint('oppId')
    )
    op.create_table('opp_genres',
    sa.Column('oppId', sa.Integer(), nullable=False),
    sa.Column('genreId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genreId'], ['genres.genreId'], ),
    sa.ForeignKeyConstraint(['oppId'], ['opportunities.oppId'], ),
    sa.PrimaryKeyConstraint('oppId', 'genreId')
    )
    op.create_table('opp_media',
    sa.Column('oppId', sa.Integer(), nullable=False),
    sa.Column('mediaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mediaId'], ['media.mediaId'], ),
    sa.ForeignKeyConstraint(['oppId'], ['opportunities.oppId'], ),
    sa.PrimaryKeyConstraint('oppId', 'mediaId')
    )
    op.create_table('opp_types',
    sa.Column('oppId', sa.Integer(), nullable=False),
    sa.Column('typeId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oppId'], ['opportunities.oppId'], ),
    sa.ForeignKeyConstraint(['typeId'], ['types.typeId'], ),
    sa.PrimaryKeyConstraint('oppId', 'typeId')
    )
    op.create_table('submissions',
    sa.Column('subId', sa.Integer(), nullable=False),
    sa.Column('creatorId', sa.Integer(), nullable=False),
    sa.Column('oppId', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Reviewing', 'Accepted', 'Rejected', 'Archived'), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('updatedDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creatorId'], ['creators.creatorId'], ),
    sa.ForeignKeyConstraint(['oppId'], ['opportunities.oppId'], ),
    sa.PrimaryKeyConstraint('subId')
    )
    op.create_table('feedback',
    sa.Column('feedbackId', sa.Integer(), nullable=False),
    sa.Column('submissionId', sa.Integer(), nullable=False),
    sa.Column('senderId', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['senderId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submissionId'], ['submissions.subId'], ),
    sa.PrimaryKeyConstraint('feedbackId')
    )
    op.create_table('sub_media',
    sa.Column('subId', sa.Integer(), nullable=False),
    sa.Column('mediaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mediaId'], ['media.mediaId'], ),
    sa.ForeignKeyConstraint(['subId'], ['submissions.subId'], ),
    sa.PrimaryKeyConstraint('subId', 'mediaId')
    )
    op.create_table('feedback_media',
    sa.Column('feedbackId', sa.Integer(), nullable=False),
    sa.Column('mediaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feedbackId'], ['feedback.feedbackId'], ),
    sa.ForeignKeyConstraint(['mediaId'], ['media.mediaId'], ),
    sa.PrimaryKeyConstraint('feedbackId', 'mediaId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_media')
    op.drop_table('sub_media')
    op.drop_table('feedback')
    op.drop_table('submissions')
    op.drop_table('opp_types')
    op.drop_table('opp_media')
    op.drop_table('opp_genres')
    op.drop_table('opportunities')
    op.drop_table('creator_types')
    op.drop_table('creator_genres')
    op.drop_table('media')
    op.drop_table('creators')
    op.drop_table('companies')
    op.drop_table('users')
    op.drop_table('types')
    op.drop_table('genres')
    # ### end Alembic commands ###
