"""empty message

Revision ID: 1b01b9ee3850
Revises:
Create Date: 2024-02-27 13:27:13.961334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b01b9ee3850'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('companyName', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('Pre-Apply', 'Denied', 'Pending', 'Approved'), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('updatedDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('creators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('Pre-Apply', 'Denied', 'Pending', 'Approved'), nullable=False),
    sa.Column('profilePic', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('updatedDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typeName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('typeName')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('Creator', 'Company'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('updatedDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('creator_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id', 'id')
    )
    op.create_table('creator_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id', 'id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('updatedDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('targetAudience', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('guidelines', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('updatedDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opp_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id', 'id')
    )
    op.create_table('opp_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id', 'id')
    )
    op.create_table('opp_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id', 'id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Reviewing', 'Accepted', 'Rejected', 'Archived'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('collaborators', sa.String(length=500), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('updatedDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submissionId', sa.Integer(), nullable=False),
    sa.Column('senderId', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['senderId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submissionId'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id', 'id')
    )
    op.create_table('feedback_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id', 'id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_media')
    op.drop_table('sub_media')
    op.drop_table('feedback')
    op.drop_table('submissions')
    op.drop_table('opp_types')
    op.drop_table('opp_media')
    op.drop_table('opp_genres')
    op.drop_table('opportunities')
    op.drop_table('media')
    op.drop_table('creator_types')
    op.drop_table('creator_genres')
    op.drop_table('users')
    op.drop_table('types')
    op.drop_table('genres')
    op.drop_table('creators')
    op.drop_table('companies')
    # ### end Alembic commands ###
