"""empty message

Revision ID: a8597aebd926
Revises: 9f8391d4d693
Create Date: 2024-05-28 17:06:08.146437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8597aebd926'
down_revision = '9f8391d4d693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_users_stripe_customer_id', ['stripe_customer_id'])
        batch_op.create_unique_constraint('uq_users_stripe_subscription_id', ['stripe_subscription_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_stripe_customer_id', type_='unique')
        batch_op.drop_constraint('uq_users_stripe_subscription_id', type_='unique')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
